# Open new windows (tabs) in the current directory
bind c new-window -c "#{pane_current_path}"

# Open horizontal splits (panes) in the current directory
bind '"' split-window -c "#{pane_current_path}"

# Open vertical splits (panes) in the current directory
bind % split-window -h -c "#{pane_current_path}"

set -g mouse on
